# Generated by Django 5.2.5 on 2025-08-19 20:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(choices=[('N', 'Normal'), ('E', 'Embarazada'), ('T', 'Tercera Edad')], max_length=1)),
                ('hora_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('atendido', models.BooleanField(default=False)),
            ],
        ),
    ]
